const projectSettingsData = [
  {
    prjSettName: 'USERTYPE',
    prjSettKey: 'USRTYP',
    prjSettDisplayName: 'Company',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'Company',
  },
  {
    prjSettName: 'USERTYPE',
    prjSettKey: 'USRTYP',
    prjSettDisplayName: 'Master',
    prjSettSortOrder: 2,
    prjSettActive: true,
    prjSettConstant: 'Master',
  },
  {
    prjSettName: 'USERTYPE',
    prjSettKey: 'USRTYP',
    prjSettDisplayName: 'Broker',
    prjSettSortOrder: 3,
    prjSettActive: true,
    prjSettConstant: 'Broker',
  },
  {
    prjSettName: 'USERTYPE',
    prjSettKey: 'USRTYP',
    prjSettDisplayName: 'Sub-Broker',
    prjSettSortOrder: 4,
    prjSettActive: true,
    prjSettConstant: 'Sub-Broker',
  },
  {
    prjSettName: 'USERTYPE',
    prjSettKey: 'USRTYP',
    prjSettDisplayName: 'Client',
    prjSettSortOrder: 5,
    prjSettActive: true,
    prjSettConstant: 'Client',
  },
  {
    prjSettName: 'Gender',
    prjSettKey: 'USRGENDER',
    prjSettDisplayName: 'Male',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'Male',
  },
  {
    prjSettName: 'Gender',
    prjSettKey: 'USRGENDER',
    prjSettDisplayName: 'Female',
    prjSettSortOrder: 2,
    prjSettActive: true,
    prjSettConstant: 'Female',
  },
  {
    prjSettName: 'City',
    prjSettKey: 'USRCITY',
    prjSettDisplayName: 'New Delhi',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'New Delhi',
  },
  {
    prjSettName: 'City',
    prjSettKey: 'USRCITY',
    prjSettDisplayName: 'Mumbai',
    prjSettSortOrder: 2,
    prjSettActive: true,
    prjSettConstant: 'Mumbai',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: 'No Time Limit',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'No Time Limit',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '5 Minute',
    prjSettSortOrder: 2,
    prjSettActive: true,
    prjSettConstant: '5 Minute',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '10 Minute',
    prjSettSortOrder: 3,
    prjSettActive: true,
    prjSettConstant: '10 Minute',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '15 Minute',
    prjSettSortOrder: 4,
    prjSettActive: true,
    prjSettConstant: '15 Minute',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '20 Minute',
    prjSettSortOrder: 5,
    prjSettActive: true,
    prjSettConstant: '20 Minute',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '30 Minute',
    prjSettSortOrder: 6,
    prjSettActive: true,
    prjSettConstant: '30 Minute',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '45 Minute',
    prjSettSortOrder: 7,
    prjSettActive: true,
    prjSettConstant: '45 Minute',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '60 Minutes',
    prjSettSortOrder: 8,
    prjSettActive: true,
    prjSettConstant: '60 Minute',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '90 Minute',
    prjSettSortOrder: 9,
    prjSettActive: true,
    prjSettConstant: '90 Minute',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '120 Minute',
    prjSettSortOrder: 10,
    prjSettActive: true,
    prjSettConstant: '120 Minute',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: '24 Hrs',
    prjSettSortOrder: 11,
    prjSettActive: true,
    prjSettConstant: '24 Hrs',
  },
  {
    prjSettName: 'User Status',
    prjSettKey: 'USRSTAT',
    prjSettDisplayName: 'Active',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'Active',
  },
  {
    prjSettName: 'User Status',
    prjSettKey: 'USRSTAT',
    prjSettDisplayName: 'Inactive',
    prjSettSortOrder: 2,
    prjSettActive: true,
    prjSettConstant: 'Inactive',
  },
  {
    prjSettName: 'User Status',
    prjSettKey: 'USRSTAT',
    prjSettDisplayName: 'Suspended',
    prjSettSortOrder: 3,
    prjSettActive: true,
    prjSettConstant: 'Suspended',
  },
  {
    prjSettName: 'User Status',
    prjSettKey: 'USRSTAT',
    prjSettDisplayName: 'Only Square Off',
    prjSettSortOrder: 4,
    prjSettActive: true,
    prjSettConstant: 'Only Square Off',
  },
  {
    prjSettName: 'USERTYPE',
    prjSettKey: 'USRTYP',
    prjSettDisplayName: 'User Type',
    prjSettSortOrder: -1,
    prjSettActive: true,
    prjSettConstant: 'User Type',
  },
  {
    prjSettName: 'Trade SquareOff Time Limit',
    prjSettKey: 'TRDSQOL',
    prjSettDisplayName: 'Trade Square Off Limit',
    prjSettSortOrder: -1,
    prjSettActive: true,
    prjSettConstant: 'Trade Square Off Limit',
  },
  {
    prjSettName: 'Transaction Type',
    prjSettKey: 'TRXNTYP',
    prjSettDisplayName: 'Credit',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'Credit',
  },
  {
    prjSettName: 'Transaction Type',
    prjSettKey: 'TRXNTYP',
    prjSettDisplayName: 'Debit',
    prjSettSortOrder: 2,
    prjSettActive: true,
    prjSettConstant: 'Debit',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Subsequent Deposit',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'Subsequent Deposit',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Subsequent Withdrawal',
    prjSettSortOrder: 2,
    prjSettActive: true,
    prjSettConstant: 'Subsequent Withdrawal',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Sell Settelment',
    prjSettSortOrder: 3,
    prjSettActive: true,
    prjSettConstant: 'Sell Settelment',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Buy Settelment',
    prjSettSortOrder: 4,
    prjSettActive: true,
    prjSettConstant: 'Buy Settelment',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Opening Balance',
    prjSettSortOrder: 5,
    prjSettActive: true,
    prjSettConstant: 'Opening Balance',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Closing Balance',
    prjSettSortOrder: 6,
    prjSettActive: true,
    prjSettConstant: 'Closing Balance',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Margin Hold',
    prjSettSortOrder: 7,
    prjSettActive: true,
    prjSettConstant: 'Margin Hold',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Margin Released',
    prjSettSortOrder: 8,
    prjSettActive: true,
    prjSettConstant: 'Margin Released',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Brokerage Collected',
    prjSettSortOrder: 9,
    prjSettActive: true,
    prjSettConstant: 'Brokerage Collected',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Brokerage Received',
    prjSettSortOrder: 10,
    prjSettActive: true,
    prjSettConstant: 'Brokerage Received',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Trade Profit',
    prjSettSortOrder: 11,
    prjSettActive: true,
    prjSettConstant: 'Trade Profit',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Trade Loss',
    prjSettSortOrder: 12,
    prjSettActive: true,
    prjSettConstant: 'Trade Loss',
  },
  {
    prjSettName: 'Margin Type',
    prjSettKey: 'MRGTYP',
    prjSettDisplayName: 'Percentage',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'Percentage',
  },
  {
    prjSettName: 'Margin Type',
    prjSettKey: 'MRGTYP',
    prjSettDisplayName: 'Per Lot',
    prjSettSortOrder: 2,
    prjSettActive: true,
    prjSettConstant: 'Per Lot',
  },
  {
    prjSettName: 'Brokerage Type',
    prjSettKey: 'BRKGTYP',
    prjSettDisplayName: 'Per Crore',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'Per Crore',
  },
  {
    prjSettName: 'Brokerage Type',
    prjSettKey: 'BRKGTYP',
    prjSettDisplayName: 'Per Lot',
    prjSettSortOrder: 2,
    prjSettActive: true,
    prjSettConstant: 'Per Lot',
  },
  {
    prjSettName: 'User Bid Settings Cmp',
    prjSettKey: 'USRBIDCMP',
    prjSettDisplayName: '1',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: '1',
  },
  {
    prjSettName: 'User Stop Settings Cmp',
    prjSettKey: 'USRSTPCMP',
    prjSettDisplayName: '1',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: '1',
  },
  {
    prjSettName: 'User MCX Bid',
    prjSettKey: 'USRMCXBID',
    prjSettDisplayName: '1000',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: '1000',
  },
  {
    prjSettName: 'User MCX Stop Amount',
    prjSettKey: 'USRMCXSTOP',
    prjSettDisplayName: '1000',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: '1000',
  },
  {
    prjSettName: 'User MCX Names',
    prjSettKey: 'USRMCXNAME',
    prjSettDisplayName: 'GOLD',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'GOLD',
  },
  {
    prjSettName: 'User MCX Names',
    prjSettKey: 'USRMCXNAME',
    prjSettDisplayName: 'SILVER',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'SILVER',
  },
  {
    prjSettName: 'User MCX Names',
    prjSettKey: 'USRMCXNAME',
    prjSettDisplayName: 'ALUMINIUM',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'ALUMINIUM',
  },
  {
    prjSettName: 'User MCX Names',
    prjSettKey: 'USRMCXNAME',
    prjSettDisplayName: 'NATURALGAS',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'NATURALGAS',
  },
  {
    prjSettName: 'User MCX Names',
    prjSettKey: 'USRMCXNAME',
    prjSettDisplayName: 'CRUDEOIL',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'CRUDEOIL',
  },
  {
    prjSettName: 'User MCX Names',
    prjSettKey: 'USRMCXNAME',
    prjSettDisplayName: 'COPPER',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'COPPER',
  },
  {
    prjSettName: 'User MCX Names',
    prjSettKey: 'USRMCXNAME',
    prjSettDisplayName: 'ALUMINI',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'ALUMINI',
  },
  {
    prjSettName: 'User MCX Names',
    prjSettKey: 'USRMCXNAME',
    prjSettDisplayName: 'ZINC',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'ZINC',
  },
  {
    prjSettName: 'Credit Balance',
    prjSettKey: 'USRCUTSETT',
    prjSettDisplayName: 'Max Loss Value/Credit Balance',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: '10',
  },
  {
    prjSettName: 'Notification',
    prjSettKey: 'USRCUTSETT',
    prjSettDisplayName: 'Max Loss Value/Notification',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: '9',
  },
  {
    prjSettName: 'Trade Square Off',
    prjSettKey: 'USRCUTSETT',
    prjSettDisplayName: 'Trade Sqaure Off Price',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'Closing Price',
  },
  {
    prjSettName: 'Lot Cutting',
    prjSettKey: 'USRCUTSETT',
    prjSettDisplayName: 'Lot Cutting Method',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'LIFO',
  },
  {
    prjSettName: 'Penalty',
    prjSettKey: 'PNLTY',
    prjSettDisplayName: 'Margin Percentage Cut',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'MRGNPER',
  },
  {
    prjSettName: 'Market Index',
    prjSettKey: 'MRKIND',
    prjSettDisplayName: '265',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'SENSEX',
  },
  {
    prjSettName: 'Market Index',
    prjSettKey: 'MRKIND',
    prjSettDisplayName: '256265',
    prjSettSortOrder: 1,
    prjSettActive: true,
    prjSettConstant: 'NIFTY 50',
  },
  {
    prjSettName: 'Market Index',
    prjSettKey: 'MRKIND',
    prjSettDisplayName: '260105',
    prjSettSortOrder: 3,
    prjSettActive: true,
    prjSettConstant: 'NIFTY BANK',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Penalty',
    prjSettSortOrder: 13,
    prjSettActive: true,
    prjSettConstant: 'Penalty',
  },
  {
    prjSettName: 'Transaction Particular',
    prjSettKey: 'TRXNPRT',
    prjSettDisplayName: 'Rent Deduction',
    prjSettSortOrder: 0,
    prjSettActive: true,
    prjSettConstant: 'Rent Deduction',
  },
  {
    prjSettName: 'Market Index',
    prjSettKey: 'MRKIND',
    prjSettDisplayName: '259849',
    prjSettSortOrder: 4,
    prjSettActive: true,
    prjSettConstant: 'NIFTY IT',
  },
];

export default projectSettingsData;
