const subMenuData = [
  {
    subMenuText: 'Create Update Client',
    subMenuConstantText: 'create-update-client',
    isSubMenuActive: true,
    menu: { id: 1 },
  },
  {
    subMenuText: 'Search Client',
    subMenuConstantText: 'search-client',
    isSubMenuActive: true,
    menu: { id: 1 },
  },
  {
    subMenuText: 'User Access Management',
    subMenuConstantText: 'user-access-management',
    isSubMenuActive: true,
    menu: { id: 1 },
  },
  {
    subMenuText: 'Perform Trades',
    subMenuConstantText: 'perform-trades',
    isSubMenuActive: true,
    menu: { id: 2 },
  },
  {
    subMenuText: 'Manage & Delete Trades',
    subMenuConstantText: 'manage-delete-trades',
    isSubMenuActive: true,
    menu: { id: 2 },
  },
  {
    subMenuText: 'Manual Reconcilations',
    subMenuConstantText: 'manual-reconcilations',
    isSubMenuActive: true,
    menu: { id: 2 },
  },
  {
    subMenuText: 'Manage Positions',
    subMenuConstantText: 'manage-positions',
    isSubMenuActive: true,
    menu: { id: 2 },
  },
  {
    subMenuText: 'Account Statement',
    subMenuConstantText: 'account-statement',
    isSubMenuActive: true,
    menu: { id: 3 },
  },
  {
    subMenuText: 'Trade Reports',
    subMenuConstantText: 'trade-reports',
    isSubMenuActive: true,
    menu: { id: 3 },
  },
  {
    subMenuText: 'P&L Reports',
    subMenuConstantText: 'pl-reports',
    isSubMenuActive: true,
    menu: { id: 3 },
  },
  {
    subMenuText: 'Brokerage Reports',
    subMenuConstantText: 'brokerage-reports',
    isSubMenuActive: true,
    menu: { id: 3 },
  },
  {
    subMenuText: 'Settelments',
    subMenuConstantText: 'settelments',
    isSubMenuActive: true,
    menu: { id: 3 },
  },
  {
    subMenuText: 'P&L and Brokerage Sharing Settings',
    subMenuConstantText: 'pl-brokerage-sharing',
    isSubMenuActive: true,
    menu: { id: 4 },
  },
  {
    subMenuText: 'Auto Cut /Bid/Stop Loss Settings',
    subMenuConstantText: 'auto-cut-settings',
    isSubMenuActive: true,
    menu: { id: 4 },
  },
  {
    subMenuText: 'Brokerage Settings',
    subMenuConstantText: 'brokerage-settings',
    isSubMenuActive: true,
    menu: { id: 4 },
  },
  {
    subMenuText: 'Trade Margin Settings',
    subMenuConstantText: 'trade-margin-settings',
    isSubMenuActive: true,
    menu: { id: 4 },
  },
  {
    subMenuText: 'Script Quantity Settings',
    subMenuConstantText: 'script-quantity-settings',
    isSubMenuActive: true,
    menu: { id: 4 },
  },
  {
    subMenuText: 'Set up Suspicious Trades',
    subMenuConstantText: 'set-suspicious-trades',
    isSubMenuActive: true,
    menu: { id: 5 },
  },
  {
    subMenuText: 'Watch Suspicious Trades',
    subMenuConstantText: 'watch-suspicious-trades',
    isSubMenuActive: true,
    menu: { id: 5 },
  },
  {
    subMenuText: 'Broad Cast Message',
    subMenuConstantText: 'broadcast-message',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
  {
    subMenuText: 'Send Alert/Notifications',
    subMenuConstantText: 'send-alert-notifications',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
  {
    subMenuText: 'Set up Theme',
    subMenuConstantText: 'set-up-theme',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
  {
    subMenuText: 'Password Change',
    subMenuConstantText: 'password-change',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
  {
    subMenuText: 'Manage App Settings',
    subMenuConstantText: 'manage-app-settings',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
  {
    subMenuText: 'Add /Update T&C',
    subMenuConstantText: 'add-updatetc',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
  {
    subMenuText: 'Advertis/Contact Us Leads',
    subMenuConstantText: 'advertis',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
  {
    subMenuText: 'Manage Support Calls',
    subMenuConstantText: 'manage-support',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
  {
    subMenuText: 'Manage Default Function',
    subMenuConstantText: 'default-function-settings',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
  {
    subMenuText: 'Manage Orders',
    subMenuConstantText: 'manage-orders',
    isSubMenuActive: true,
    menu: { id: 2 },
  },
  {
    subMenuText: 'Watch Logs',
    subMenuConstantText: 'watch-logs',
    isSubMenuActive: true,
    menu: { id: 6 },
  },
];

export default subMenuData;
