const watchlistData = [
  {
    name: 'Watchlist 1',
    scripts: [],
    columns: [
      { id: 1, width: '70px' },
      { id: 2, width: '70px' },
      { id: 3, width: '70px' },
      { id: 4, width: '70px' },
      { id: 5, width: '80px' },
      { id: 6, width: '110px' },
      { id: 3, width: '130px' },
      { id: 7, width: '110px' },
      { id: 8, width: '70px' },
      { id: 9, width: '70px' },
      { id: 10, width: '110px' },
      { id: 11, width: '90px' },
      { id: 12, width: '80px' },
      { id: 13, width: '80px' },
      { id: 14, width: '80px' },
      { id: 15, width: '80px' },
    ],
    index: 1,
    user: {
      id: 1,
    },
  },
  {
    name: 'Watchlist 2',
    scripts: [],
    columns: [
      { id: 1, width: '70px' },
      { id: 2, width: '70px' },
      { id: 3, width: '70px' },
      { id: 4, width: '70px' },
      { id: 5, width: '80px' },
      { id: 6, width: '110px' },
      { id: 3, width: '130px' },
      { id: 7, width: '110px' },
      { id: 8, width: '70px' },
      { id: 9, width: '70px' },
      { id: 10, width: '110px' },
      { id: 11, width: '90px' },
      { id: 12, width: '80px' },
      { id: 13, width: '80px' },
      { id: 14, width: '80px' },
      { id: 15, width: '80px' },
    ],
    index: 2,
    user: {
      id: 1,
    },
  },
  {
    name: 'Watchlist 3',
    scripts: [],
    columns: [
      { id: 1, width: '70px' },
      { id: 2, width: '70px' },
      { id: 3, width: '70px' },
      { id: 4, width: '70px' },
      { id: 5, width: '80px' },
      { id: 6, width: '110px' },
      { id: 3, width: '130px' },
      { id: 7, width: '110px' },
      { id: 8, width: '70px' },
      { id: 9, width: '70px' },
      { id: 10, width: '110px' },
      { id: 11, width: '90px' },
      { id: 12, width: '80px' },
      { id: 13, width: '80px' },
      { id: 14, width: '80px' },
      { id: 15, width: '80px' },
    ],
    index: 3,
    user: {
      id: 1,
    },
  },
  {
    name: 'Watchlist 3',
    scripts: [],
    columns: [
      { id: 1, width: '70px' },
      { id: 2, width: '70px' },
      { id: 3, width: '70px' },
      { id: 4, width: '70px' },
      { id: 5, width: '80px' },
      { id: 6, width: '110px' },
      { id: 3, width: '130px' },
      { id: 7, width: '110px' },
      { id: 8, width: '70px' },
      { id: 9, width: '70px' },
      { id: 10, width: '110px' },
      { id: 11, width: '90px' },
      { id: 12, width: '80px' },
      { id: 13, width: '80px' },
      { id: 14, width: '80px' },
      { id: 15, width: '80px' },
    ],
    index: 4,
    user: {
      id: 1,
    },
  },
];

export default watchlistData;
