export const ResponseType = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  UNAUTHORISED: 'UNAUTHORISED',
  MULTIPLE_LOGIN: 'MULTIPLE_LOGIN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  RESET_REQUIRED: 'RESET_REQUIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};
