export const columns = {
  instrumentToken: 1,
  exchange: 1,
  symbol: 2,
  expiry: 3,
  lotSize: 4,
  buyQty: 5,
  buyPrice: 6,
  sellPrice: 7,
  sellQty: 8,
  ltp: 9,
  change: 10,
  'change%': 11,
  open: 1,
  high: 1,
  low: 1,
  close: 1,
  isSelected: 1,
  buy_price_status: 1,
  buy_qty_status: 1,
  change_status: 1,
  ltp_status: 1,
  sell_price_status: 1,
  sell_qty_status: 1,
};
